/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CouponCoupon from '../model/CouponCoupon';

/**
* Coupon service.
* @module api/CouponApi
* @version 2.0
*/
export default class CouponApi {

    /**
    * Constructs a new CouponApi. 
    * @alias module:api/CouponApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1CouponsGet operation.
     * @callback module:api/CouponApi~v1CouponsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CouponCoupon>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get all existing Coupons
     * Get all existing Coupons.
     * @param {module:api/CouponApi~v1CouponsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CouponCoupon>}
     */
    v1CouponsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CouponCoupon];
      return this.apiClient.callApi(
        '/v1/coupons', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1CouponsIdDelete operation.
     * @callback module:api/CouponApi~v1CouponsIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete Coupon by given ID
     * Delete Coupon by given ID.
     * @param {String} id Coupon ID
     * @param {module:api/CouponApi~v1CouponsIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    v1CouponsIdDelete(id, callback) {
      let postBody = id;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling v1CouponsIdDelete");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/v1/coupons/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1CouponsIdGet operation.
     * @callback module:api/CouponApi~v1CouponsIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CouponCoupon} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Coupon by given ID or 404 error.
     * Get Coupon by given ID or 404 error.
     * @param {String} id Coupon ID
     * @param {module:api/CouponApi~v1CouponsIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CouponCoupon}
     */
    v1CouponsIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling v1CouponsIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CouponCoupon;
      return this.apiClient.callApi(
        '/v1/coupons/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1CouponsIdPost operation.
     * @callback module:api/CouponApi~v1CouponsIdPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CouponCoupon} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update Coupon
     * Update Coupon.
     * @param {String} id Coupon ID
     * @param {module:api/CouponApi~v1CouponsIdPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CouponCoupon}
     */
    v1CouponsIdPost(id, callback) {
      let postBody = id;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling v1CouponsIdPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CouponCoupon;
      return this.apiClient.callApi(
        '/v1/coupons/{id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1CouponsPost operation.
     * @callback module:api/CouponApi~v1CouponsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CouponCoupon} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create a new Coupon
     * Create a new Coupon.
     * @param {module:api/CouponApi~v1CouponsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CouponCoupon}
     */
    v1CouponsPost(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CouponCoupon;
      return this.apiClient.callApi(
        '/v1/coupons', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
