/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DiscountDiscount from '../model/DiscountDiscount';

/**
* Discount service.
* @module api/DiscountApi
* @version 2.0
*/
export default class DiscountApi {

    /**
    * Constructs a new DiscountApi. 
    * @alias module:api/DiscountApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1CustomersIdDiscountGet operation.
     * @callback module:api/DiscountApi~v1CustomersIdDiscountGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DiscountDiscount>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get all existing Discounts
     * Get all existing Discounts.
     * @param {module:api/DiscountApi~v1CustomersIdDiscountGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DiscountDiscount>}
     */
    v1CustomersIdDiscountGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [DiscountDiscount];
      return this.apiClient.callApi(
        '/v1/customers/{id}/discount', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1CustomersIdDiscountIdDelete operation.
     * @callback module:api/DiscountApi~v1CustomersIdDiscountIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete Discount by given ID
     * Delete Discount by given ID.
     * @param {String} id Discount ID
     * @param {module:api/DiscountApi~v1CustomersIdDiscountIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    v1CustomersIdDiscountIdDelete(id, callback) {
      let postBody = id;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling v1CustomersIdDiscountIdDelete");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/v1/customers/{id}/discount/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1CustomersIdDiscountIdGet operation.
     * @callback module:api/DiscountApi~v1CustomersIdDiscountIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DiscountDiscount} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Discount by given ID or 404 error.
     * Get Discount by given ID or 404 error.
     * @param {String} id Discount ID
     * @param {module:api/DiscountApi~v1CustomersIdDiscountIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DiscountDiscount}
     */
    v1CustomersIdDiscountIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling v1CustomersIdDiscountIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DiscountDiscount;
      return this.apiClient.callApi(
        '/v1/customers/{id}/discount/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1CustomersIdDiscountIdPost operation.
     * @callback module:api/DiscountApi~v1CustomersIdDiscountIdPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DiscountDiscount} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update Discount
     * Update Discount.
     * @param {String} id Discount ID
     * @param {module:api/DiscountApi~v1CustomersIdDiscountIdPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DiscountDiscount}
     */
    v1CustomersIdDiscountIdPost(id, callback) {
      let postBody = id;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling v1CustomersIdDiscountIdPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = DiscountDiscount;
      return this.apiClient.callApi(
        '/v1/customers/{id}/discount/{id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1CustomersIdDiscountPost operation.
     * @callback module:api/DiscountApi~v1CustomersIdDiscountPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DiscountDiscount} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create a new Discount
     * Create a new Discount.
     * @param {module:api/DiscountApi~v1CustomersIdDiscountPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DiscountDiscount}
     */
    v1CustomersIdDiscountPost(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DiscountDiscount;
      return this.apiClient.callApi(
        '/v1/customers/{id}/discount', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
