/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DisputeDispute from '../model/DisputeDispute';

/**
* Dispute service.
* @module api/DisputeApi
* @version 2.0
*/
export default class DisputeApi {

    /**
    * Constructs a new DisputeApi. 
    * @alias module:api/DisputeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1DisputesGet operation.
     * @callback module:api/DisputeApi~v1DisputesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DisputeDispute>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get all existing Disputes
     * Get all existing Disputes.
     * @param {module:api/DisputeApi~v1DisputesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DisputeDispute>}
     */
    v1DisputesGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [DisputeDispute];
      return this.apiClient.callApi(
        '/v1/disputes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1DisputesIdClosePost operation.
     * @callback module:api/DisputeApi~v1DisputesIdClosePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DisputeDispute} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * close Dispute
     * Close Dispute.
     * @param {String} id Dispute ID
     * @param {module:api/DisputeApi~v1DisputesIdClosePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DisputeDispute}
     */
    v1DisputesIdClosePost(id, callback) {
      let postBody = id;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling v1DisputesIdClosePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = DisputeDispute;
      return this.apiClient.callApi(
        '/v1/disputes/{id}/close', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1DisputesIdDelete operation.
     * @callback module:api/DisputeApi~v1DisputesIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete Dispute by given ID
     * Delete Dispute by given ID.
     * @param {String} id Dispute ID
     * @param {module:api/DisputeApi~v1DisputesIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    v1DisputesIdDelete(id, callback) {
      let postBody = id;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling v1DisputesIdDelete");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/v1/disputes/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1DisputesIdGet operation.
     * @callback module:api/DisputeApi~v1DisputesIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DisputeDispute} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Dispute by given ID or 404 error.
     * Get Dispute by given ID or 404 error.
     * @param {String} id Dispute ID
     * @param {module:api/DisputeApi~v1DisputesIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DisputeDispute}
     */
    v1DisputesIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling v1DisputesIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DisputeDispute;
      return this.apiClient.callApi(
        '/v1/disputes/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1DisputesIdPost operation.
     * @callback module:api/DisputeApi~v1DisputesIdPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DisputeDispute} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update Dispute
     * Update Dispute.
     * @param {String} id Dispute ID
     * @param {module:api/DisputeApi~v1DisputesIdPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DisputeDispute}
     */
    v1DisputesIdPost(id, callback) {
      let postBody = id;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling v1DisputesIdPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = DisputeDispute;
      return this.apiClient.callApi(
        '/v1/disputes/{id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1DisputesPost operation.
     * @callback module:api/DisputeApi~v1DisputesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DisputeDispute} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create a new Dispute
     * Create a new Dispute.
     * @param {module:api/DisputeApi~v1DisputesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DisputeDispute}
     */
    v1DisputesPost(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DisputeDispute;
      return this.apiClient.callApi(
        '/v1/disputes', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
