export const chile = [
    "Antofagasta",
    "Araucanía",
    "Arica y Parinacota",
    "Atacama",
    "Aysén del General Carlos Ibáñez del Campo",
    "Biobío",
    "Coquimbo",
    "Libertador General Bernardo O'Higgins",
    "Los Lagos",
    "Los Ríos",
    "Magallanes y de la Antártica Chilena",
    "Maule",
    "Metropolitana de Santiago",
    "Tarapacá",
    "Valparaíso",
]