export const china = [
    "安徽省 — Anhui Sheng",
    "澳门 — Macau",
    "北京市 — Beijing Shi",
    "重庆市 — Chongqing Shi",
    "福建省 — Fujian Sheng",
    "甘肃省 — Gansu Sheng",
    "广东省 — Guangdong Sheng",
    "广西 — Guangxi Zhuangzuzizhiqu",
    "贵州省 — Guizhou Sheng",
    "海南省 — Hainan Sheng",
    "河北省 — Hebei Sheng",
    "河南省 — Henan Sheng",
    "黑龙江省 — Heilongjiang Sheng",
    "湖北省 — Hubei Sheng",
    "湖南省 — Hunan Sheng",
    "吉林省 — Jilin Sheng",
    "江苏省 — Jiangsu Sheng",
    "江西省 — Jiangxi Sheng",
    "辽宁省 — Liaoning Sheng",
    "内蒙古 — Neimenggu Zizhiqu",
    "宁夏 — Ningxia Huizuzizhiqu",
    "青海省 — Qinghai Sheng",
    "山东省 — Shandong Sheng",
    "山西省 — Shanxi Sheng",
    "陕西省 — Shaanxi Sheng",
    "上海市 — Shanghai Shi",
    "四川省 — Sichuan Sheng",
    "台湾 — Taiwan",
    "天津市 — Tianjin Shi",
    "西藏 — Xizang Zizhiqu",
    "香港 — Hong Kong",
    "新疆 — Xinjiang Weiwuerzizhiqu",
    "云南省 — Yunnan Sheng",
    "浙江省 — Zhejiang Sheng",
]