export const egypt = [
    "أسوان — Aswan Governorate",
    "أسيوط — Asyut Governorate",
    "الإسكندرية — Alexandria Governorate",
    "الإسماعيلية — Ismailia Governorate",
    "الأقصر — Luxor Governorate",
    "البحر الأحمر — Red Sea Governorate",
    "البحيرة — El Beheira Governorate",
    "الجيزة — Giza Governorate",
    "الدقهلية — Dakahlia Governorate",
    "السويس — Suez Governorate",
    "الشرقية — Ash Sharqia Governorate",
    "الغربية — Gharbia Governorate",
    "الفيوم — Faiyum Governorate",
    "القاهرة — Cairo Governorate",
    "القليوبية — Qalyubia Governorate",
    "المنوفية — Menofia Governorate",
    "المنيا — Menia Governorate",
    "الوادي الجديد — New Valley Governorate",
    "بني سويف — Beni Suef Governorate",
    "بورسعيد — Port Said Governorate",
    "جنوب سيناء — South Sinai Governorate",
    "دمياط — Damietta Governorate",
    "سوهاج — Sohag Governorate",
    "شمال سيناء — North Sinai Governorate",
    "قنا — Qena Governorate",
    "كفر الشيخ — Kafr El Sheikh Governorate",
    "مطروح — Matrouh Governorate",
]