export const iraq = [
    "Al Anbar Governorate",
    "Basra Governorate",
    "Muthanna Governorate",
    "Al-Qadisiyah Governorate",
    "Najaf Governorate",
    "Erbil Governorate",
    "Sulaymaniyah Governorate",
    "Babil Governorate",
    "Baghdad Governorate",
    "Dohuk Governorate",
    "Dhi Qar Governorate",
    "Diyala Governorate",
    "Karbala Governorate",
    "Kirkuk Governorate",
    "Maysan Governorate",
    "Nineveh Governorate",
    "Saladin Governorate",
    "Wasit Governorate",
]