export const kazakhstan = [
    "Almaty",
    "Astana",
    "Almatinskaya oblast'",
    "Akmolinskaya oblast'",
    "Aktyubinskaya oblast'",
    "Atyrauskaya oblast'",
    "Baykonyr",
    "Zapadno-Kazakhstanskaya oblast'",
    "Mangistauskaya oblast'",
    "Yuzhno-Kazakhstankaya oblast'",
    "Pavlodarskaya oblast'",
    "Karagandinskaya oblast'",
    "Kostanayskaya oblast'",
    "Kyzylordinskaya oblast'",
    "Vostochno-Kazakhstanskaya oblast'",
    "Severo-Kazakhstanskaya oblast'",
    "Zhambylskaya oblast'",
]