export const mongolia = [
    "Ulaanbaatar",
    "Arkhangai Province",
    "Bayankhongor Province",
    "Bayan-Ölgii Province",
    "Bulgan Province",
    "Darkhan-Uul Province",
    "Dornod Province",
    "Dornogovi Province",
    "Dundgovi Province",
    "Zavkhan Province",
    "Govi-Altai Province",
    "Govisümber Province",
    "Khentii Province",
    "Khovd Province",
    "Khövsgöl Province",
    "Ömnögovi Province",
    "Orkhon Province",
    "Övörkhangai Province",
    "Selenge Province",
    "Sükhbaatar Province",
    "Töv Province",
    "Uvs Province",
]