export const nicaragua = [
    "Boaco",
    "Carazo",
    "Chinandega",
    "Chontales",
    "Estelí",
    "Granada",
    "Jinotega",
    "León",
    "Madriz",
    "Managua",
    "Masaya",
    "Matagalpa",
    "Nueva Segovia",
    "Región Autónoma de la Costa Caribe Norte",
    "Región Autónoma de la Costa Caribe Sur",
    "Río San Juan",
    "Rivas",
]