export const papuanewguinea = [
    "National Capital District",
    "Central",
    "Chimbu",
    "Eastern Highlands",
    "East New Britain",
    "East Sepik",
    "Enga",
    "Gulf",
    "Hela",
    "Jiwaka",
    "Madang",
    "Manus",
    "Milne Bay",
    "Morobe",
    "New Ireland",
    "Northern",
    "West Sepik",
    "Southern Highlands",
    "Western",
    "Western Highlands",
    "West New Britain",
    "Bougainville",
]