export const russia = [
    "Алтайский край — Altayskiy kray",
    "Амурская область — Amurskaya oblast'",
    "Архангельская область — Arkhangelskaya oblast'",
    "Астраханская область — Astrakhanskaya oblast'",
    "Белгородская область — Belgorodskaya oblast'",
    "Брянская область — Bryanskaya oblast'",
    "Владимирская область — Vladimirskaya oblast'",
    "Волгоградская область — Volgogradskaya oblast'",
    "Вологодская область — Vologodskaya oblast'",
    "Воронежская область — Voronezhskaya oblast'",
    "Еврейская автономная область — Evreyskaya avtonomnaya oblast'",
    "Забайкальский край — Zabaykalskiy kray",
    "Ивановская область — Ivanovskaya oblast'",
    "Иркутская область — Irkutskaya oblast'",
    "Кабардино-Балкарская Республика — Kabardino-Balkarskaya Republits",
    "Калининградская область — Kaliningradskaya oblast'",
    "Калужская область — Kaluzhskaya oblast'",
    "Камчатский край — Kamchatskiy kray",
    "Карачаево-Черкесская Республика — Karachaevo-Cherkesskaya Republits",
    "Кемеровская область — Kemerovskaya oblast'",
    "Кировская область — Kirovskaya oblast'",
    "Костромская область — Kostromskaya oblast'",
    "Краснодарский край — Krasnodarskiy kray",
    "Красноярский край — Krasnoyarskiy kray",
    "Курганская область — Kurganskaya oblast'",
    "Курская область — Kurskaya oblast'",
    "Ленинградская область — Leningradskaya oblast'",
    "Липецкая область — Lipetskaya oblast'",
    "Магаданская область — Magadanskaya oblast'",
    "Москва — Moskva",
    "Московская область — Moskovskaya oblast'",
    "Мурманская область — Murmanskaya oblast'",
    "Ненецкий автономный округ — Nenetskiy",
    "Нижегородская область — Nizhegorodskaya oblast'",
    "Новгородская область — Novgorodskaya oblast'",
    "Новосибирская область — Novosibirskaya oblast'",
    "Омская область — Omskaya oblast'",
    "Оренбургская область — Orenburgskaya oblast'",
    "Орловская область — Orlovskaya oblast'",
    "Пензенская область — Penzenskaya oblast'",
    "Пермский край — Permskiy kray",
    "Приморский край — Primorskiy kray",
    "Псковская область — Pskovskaya oblast'",
    "Республика Адыгея — Respublika Adygeya",
    "Республика Алтай — Altay Republits",
    "Республика Башкортостан — Bashkortostan Republits",
    "Республика Бурятия — Buryatiya Republits",
    "Республика Дагестан — Dagestan Republits",
    "Республика Ингушетия — Ingushetiya Republits",
    "Республика Калмыкия — Respublika Kalmykiya",
    "Республика Карелия — Kareliya Republits",
    "Республика Коми — Komi Republits",
    "Республика Крым — Respublika Krym",
    "Республика Марий Эл — Respublika Mariy El",
    "Республика Мордовия — Respublika Mordoviya",
    "Республика Caxa (Якутия) — Sakha (Yakutiya) Republits",
    "Республика Северная Осетия-Алания — Respublika Severnaya Osetiya-Alaniya",
    "Республика Татарстан — Respublika Tatarstan",
    "Республика Тыва — Tyva Republits",
    "Республика Удмуртия — Respublika Udmurtiya",
    "Республика Хакасия — Khakasiya Republits",
    "Ростовская область — Rostovskaya oblast'",
    "Рязанская область — Ryazanskaya oblast'",
    "Самарская область — Samarskaya oblast'",
    "Санкт-Петербург — Sankt-Peterburg",
    "Саратовская область — Saratovskaya oblast'",
    "Сахалинская область — Sakhalinskaya oblast'",
    "Свердловская область — Sverdlovskaya oblast'",
    "Севастополь — Sevastopol'",
    "Смоленская область — Smolenskaya oblast'",
    "Ставропольский край — Stavropolskiy kray",
    "Тамбовская область — Tambovskaya oblast'",
    "Тверская область — Tverskaya oblast'",
    "Томская область — Tomskaya oblast'",
    "Тульская область — Tulskaya oblast'",
    "Тюменская область — Tyumenskaya oblast'",
    "Ульяновская область — Ulyanovskaya oblast'",
    "Хабаровский край — Khabarovskiy kray",
    "Ханты-Мансийский автономный округ — Khanty-Mansiyskiy avtonomnyy okrug",
    "Челябинская область — Chelyabinskaya oblast'",
    "Чеченская Республика — Chechenskaya Republits",
    "Чувашская Республика — Chuvashia",
    "Чукотский автономный округ — Chukotskiy",
    "Ямало-Ненецкий автономный округ — Yamalo-Nenetskiy",
    "Ярославская область — Yaroslavskaya oblast'",
]