export const southkorea = [
    "강원 — Gangwon-do",
    "경기 — Gyeonggi-do",
    "경남 — Gyeongsangnam-do",
    "경북 — Gyeongsangbuk-do",
    "광주 — Gwangju",
    "대구 — Daegu",
    "대전 — Daejeon",
    "부산 — Busan",
    "서울 — Seoul",
    "세종 — Sejong",
    "울산 — Ulsan",
    "인천 — Incheon",
    "전남 — Jeollanam-do",
    "전북 — Jeollabuk-do",
    "제주 — Jeju-do",
    "충남 — Chungcheongnam-do",
    "충북 — Chungcheongbuk-do",
]