export const taiwan = [
    "台中市 — Taichung City",
    "台北市 — Taipei City",
    "台東縣 — Taitung County",
    "台南市 — Tainan City",
    "宜蘭縣 — Yilan County",
    "花蓮縣 — Hualien County",
    "金門縣 — Kinmen County",
    "南投縣 — Nantou County",
    "屏東縣 — Pingtung County",
    "苗栗縣 — Miaoli County",
    "桃園市 — Taoyuan City",
    "高雄市 — Kaohsiung City",
    "基隆市 — Keelung City",
    "連江縣 — Lienchiang County",
    "雲林縣 — Yunlin County",
    "新北市 — New Taipei City",
    "新竹市 — Hsinchu City",
    "新竹縣 — Hsinchu County",
    "嘉義市 — Chiayi City",
    "嘉義縣 — Chiayi County",
    "彰化縣 — Changhua County",
    "澎湖縣 — Penghu County",
]