export const ukraine = [
    "Автономна Республіка Крим — Crimea",
    "Вінницька область — Vinnyts'ka oblast",
    "Волинська область — Volyns'ka oblast",
    "Дніпропетровська область — Dnipropetrovsk oblast",
    "Донецька область — Donetsk oblast",
    "Житомирська область — Zhytomyrs'ka oblast",
    "Закарпатська область — Zakarpats'ka oblast",
    "Запорізька область — Zaporiz'ka oblast",
    "Івано-Франківська область — Ivano-Frankivs'ka oblast",
    "Київ — Kyiv city",
    "Київська область — Kiev oblast",
    "Кіровоградська область — Kirovohrads'ka oblast",
    "Луганська область — Luhans'ka oblast",
    "Львівська область — Lviv oblast",
    "Миколаївська область — Mykolaivs'ka oblast",
    "Одеська область — Odessa oblast",
    "Полтавська область — Poltavs'ka oblast",
    "Рівненська область — Rivnens'ka oblast",
    "Севастополь — Sevastopol' city",
    "Сумська область — Sums'ka oblast",
    "Тернопільська область — Ternopil's'ka oblast",
    "Харківська область — Kharkiv oblast",
    "Херсонська область — Khersons'ka oblast",
    "Хмельницька область — Khmel'nyts'ka oblast",
    "Черкаська область — Cherkas'ka oblast",
    "Чернівецька область — Chernivets'ka oblast",
    "Чернігівська область — Chernihivs'ka oblast",
]