export const vietnam = [
    "An Giang — An Giang Province",
    "Bà Rịa-Vũng Tàu — Ba Ria-Vung Tau Province",
    "Bạc Liêu — Bac Lieu Province",
    "Bắc Giang — Bac Giang Province",
    "Bắc Kạn — Bac Kan Province",
    "Bắc Ninh — Bac Ninh Province",
    "Bến Tre — Ben Tre Province",
    "Bình Dương — Binh Duong Province",
    "Bình Định — Binh Dinh Province",
    "Bình Phước — Binh Phuoc Province",
    "Bình Thuận — Binh Thuan Province",
    "Cà Mau — Ca Mau Province",
    "Cao Bằng — Cao Bang Province",
    "Cần Thơ — Can Tho City",
    "Đà Nẵng — Da Nang City",
    "Đắk Lắk — Dak Lak Province",
    "Đăk Nông — Dak Nong Province",
    "Điện Biên — Dien Bien Province",
    "Đồng Nai — Dong Nai Province",
    "Đồng Tháp — Dong Thap Province",
    "Gia Lai — Gia Lai Province",
    "Hà Giang — Ha Giang Province",
    "Hà Nam — Ha Nam Province",
    "Hà Nội — Hanoi City",
    "Hà Tĩnh — Ha Tinh Province",
    "Hải Dương — Hai Duong Province",
    "Hải Phòng — Haiphong City",
    "Hậu Giang — Hau Giang Province",
    "Hòa Bình — Hoa Binh Province",
    "Hưng Yên — Hung Yen Province",
    "Khánh Hòa — Khanh Hoa Province",
    "Kiên Giang — Kien Giang Province",
    "Kon Tum — Kon Tum Province",
    "Lai Châu — Lai Chau Province",
    "Lạng Sơn — Lang Song Province",
    "Lào Cai — Lao Cai Province",
    "Lâm Đồng — Lam Dong Province",
    "Long An — Long An Province",
    "Nam Định — Nam Dinh Province",
    "Nghệ An — Nghe An Province",
    "Ninh Bình — Ninh Binh Province",
    "Ninh Thuận — Ninh Thuan Province",
    "Phú Thọ — Phu Tho Province",
    "Phú Yên — Phu Yen Province",
    "Quảng Bình — Quang Binh Province",
    "Quảng Nam — Quang Nam Province",
    "Quảng Ngãi — Quang Ngai Province",
    "Quảng Ninh — Quang Ninh Province",
    "Quảng Trị — Quang Tri Province",
    "Sóc Trăng — Soc Trang Province",
    "Sơn La — Son La Province",
    "Tây Ninh — Tay Ninh Province",
    "Thái Bình — Thai Binh Province",
    "Thái Nguyên — Thai Nguyen Province",
    "Thanh Hóa — Thanh Hoa Province",
    "Thành phố Hồ Chí Minh — Ho Chi Minh City",
    "Thừa Thiên–Huế — Thua Thien-Hue Province",
    "Tiền Giang — Tien Giang Province",
    "Trà Vinh — Tra Vinh Province",
    "Tuyên Quang — Tuyen Quang Province",
    "Vĩnh Long — Vinh Long Province",
    "Vĩnh Phúc — Vinh Phuc Province",
    "Yên Bái — Yen Bai Province",
]