/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FiberSwaggerExampleApi);
  }
}(this, function(expect, FiberSwaggerExampleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FiberSwaggerExampleApi.BankBankAccount();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BankBankAccount', function() {
    it('should create an instance of BankBankAccount', function() {
      // uncomment below and update the code to test BankBankAccount
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be.a(FiberSwaggerExampleApi.BankBankAccount);
    });

    it('should have the property account (base name: "account")', function() {
      // uncomment below and update the code to test the property account
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property accountHolderName (base name: "account_holder_name")', function() {
      // uncomment below and update the code to test the property accountHolderName
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property accountHolderType (base name: "account_holder_type")', function() {
      // uncomment below and update the code to test the property accountHolderType
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property accountId (base name: "account_id")', function() {
      // uncomment below and update the code to test the property accountId
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property accountType (base name: "account_type")', function() {
      // uncomment below and update the code to test the property accountType
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property availablePayoutMethods (base name: "available_payout_methods")', function() {
      // uncomment below and update the code to test the property availablePayoutMethods
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property bankName (base name: "bank_name")', function() {
      // uncomment below and update the code to test the property bankName
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property customer (base name: "customer")', function() {
      // uncomment below and update the code to test the property customer
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property customerId (base name: "customer_id")', function() {
      // uncomment below and update the code to test the property customerId
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property defaultForCurrency (base name: "default_for_currency")', function() {
      // uncomment below and update the code to test the property defaultForCurrency
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property deletedAt (base name: "deleted_at")', function() {
      // uncomment below and update the code to test the property deletedAt
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property fingerprint (base name: "fingerprint")', function() {
      // uncomment below and update the code to test the property fingerprint
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property last4 (base name: "last4")', function() {
      // uncomment below and update the code to test the property last4
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property livemode (base name: "livemode")', function() {
      // uncomment below and update the code to test the property livemode
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property object (base name: "object")', function() {
      // uncomment below and update the code to test the property object
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property routingNumber (base name: "routing_number")', function() {
      // uncomment below and update the code to test the property routingNumber
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new FiberSwaggerExampleApi.BankBankAccount();
      //expect(instance).to.be();
    });

  });

}));
