/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FiberSwaggerExampleApi);
  }
}(this, function(expect, FiberSwaggerExampleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FiberSwaggerExampleApi.CouponCoupon();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CouponCoupon', function() {
    it('should create an instance of CouponCoupon', function() {
      // uncomment below and update the code to test CouponCoupon
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be.a(FiberSwaggerExampleApi.CouponCoupon);
    });

    it('should have the property amountOff (base name: "amount_off")', function() {
      // uncomment below and update the code to test the property amountOff
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property appliesTo (base name: "applies_to")', function() {
      // uncomment below and update the code to test the property appliesTo
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property deletedAt (base name: "deleted_at")', function() {
      // uncomment below and update the code to test the property deletedAt
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property durationInMonths (base name: "duration_in_months")', function() {
      // uncomment below and update the code to test the property durationInMonths
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property livemode (base name: "livemode")', function() {
      // uncomment below and update the code to test the property livemode
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property maxRedemptions (base name: "max_redemptions")', function() {
      // uncomment below and update the code to test the property maxRedemptions
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property object (base name: "object")', function() {
      // uncomment below and update the code to test the property object
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property percentOff (base name: "percent_off")', function() {
      // uncomment below and update the code to test the property percentOff
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property redeemBy (base name: "redeem_by")', function() {
      // uncomment below and update the code to test the property redeemBy
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property timesRedeemed (base name: "times_redeemed")', function() {
      // uncomment below and update the code to test the property timesRedeemed
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

    it('should have the property valid (base name: "valid")', function() {
      // uncomment below and update the code to test the property valid
      //var instance = new FiberSwaggerExampleApi.CouponCoupon();
      //expect(instance).to.be();
    });

  });

}));
