/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FiberSwaggerExampleApi);
  }
}(this, function(expect, FiberSwaggerExampleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PromotionPromotionCode', function() {
    it('should create an instance of PromotionPromotionCode', function() {
      // uncomment below and update the code to test PromotionPromotionCode
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be.a(FiberSwaggerExampleApi.PromotionPromotionCode);
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property coupon (base name: "coupon")', function() {
      // uncomment below and update the code to test the property coupon
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property customer (base name: "customer")', function() {
      // uncomment below and update the code to test the property customer
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property deletedAt (base name: "deleted_at")', function() {
      // uncomment below and update the code to test the property deletedAt
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property expiresAt (base name: "expires_at")', function() {
      // uncomment below and update the code to test the property expiresAt
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property firstTimeTransaction (base name: "first_time_transaction")', function() {
      // uncomment below and update the code to test the property firstTimeTransaction
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property livemode (base name: "livemode")', function() {
      // uncomment below and update the code to test the property livemode
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property maxRedemptions (base name: "max_redemptions")', function() {
      // uncomment below and update the code to test the property maxRedemptions
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property minimumAmount (base name: "minimum_amount")', function() {
      // uncomment below and update the code to test the property minimumAmount
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property minimumAmountCurrency (base name: "minimum_amount_currency")', function() {
      // uncomment below and update the code to test the property minimumAmountCurrency
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property object (base name: "object")', function() {
      // uncomment below and update the code to test the property object
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property timesRedeemed (base name: "times_redeemed")', function() {
      // uncomment below and update the code to test the property timesRedeemed
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new FiberSwaggerExampleApi.PromotionPromotionCode();
      //expect(instance).to.be();
    });

  });

}));
