/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CheckoutBillingAddressCollection } from './checkoutBillingAddressCollection';
import { CheckoutCustomerCreation } from './checkoutCustomerCreation';
import { CheckoutLocale } from './checkoutLocale';
import { CheckoutMode } from './checkoutMode';
import { CheckoutPaymentMethodCollection } from './checkoutPaymentMethodCollection';
import { CheckoutPaymentStatus } from './checkoutPaymentStatus';
import { CheckoutStatus } from './checkoutStatus';
import { CheckoutSubmitType } from './checkoutSubmitType';
import { DatabaseDeletedAt } from './databaseDeletedAt';

export class CheckoutCheckoutSession {
    'afterExpiration'?: string;
    'allowPromotionCodes'?: boolean;
    'amountSubtotal'?: number;
    'amountTotal'?: number;
    'automaticTax'?: boolean;
    'billingAddressCollection'?: CheckoutBillingAddressCollection;
    'cancelUrl'?: string;
    'clientReferenceId'?: string;
    'consent'?: string;
    'consentCollection'?: string;
    'createdAt'?: string;
    'currency'?: string;
    'customText'?: string;
    'customer'?: string;
    'customerCreation'?: CheckoutCustomerCreation;
    'customerDetails'?: string;
    'customerEmail'?: string;
    'deletedAt'?: DatabaseDeletedAt;
    'expiresAt'?: number;
    'id'?: string;
    'invoice'?: string;
    'invoiceCreation'?: string;
    'lineItems'?: Array<string>;
    'livemode'?: boolean;
    'locale'?: CheckoutLocale;
    'metadata'?: object;
    'mode'?: CheckoutMode;
    'object'?: string;
    'paymentIntent'?: string;
    'paymentLink'?: string;
    'paymentMethodCollection'?: CheckoutPaymentMethodCollection;
    'paymentMethodOptions'?: string;
    'paymentMethodTypes'?: Array<string>;
    'paymentStatus'?: CheckoutPaymentStatus;
    'phoneNumberCollection'?: boolean;
    'recoveredFrom'?: string;
    'setupIntent'?: string;
    'shippingAddressCollection'?: string;
    'shippingCost'?: string;
    'shippingDetails'?: string;
    'shippingOptions'?: Array<string>;
    'status'?: CheckoutStatus;
    'submitType'?: CheckoutSubmitType;
    'subscription'?: string;
    'successUrl'?: string;
    'taxIdCollection'?: boolean;
    'totalDetails'?: string;
    'updatedAt'?: string;
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "afterExpiration",
            "baseName": "after_expiration",
            "type": "string"
        },
        {
            "name": "allowPromotionCodes",
            "baseName": "allow_promotion_codes",
            "type": "boolean"
        },
        {
            "name": "amountSubtotal",
            "baseName": "amount_subtotal",
            "type": "number"
        },
        {
            "name": "amountTotal",
            "baseName": "amount_total",
            "type": "number"
        },
        {
            "name": "automaticTax",
            "baseName": "automatic_tax",
            "type": "boolean"
        },
        {
            "name": "billingAddressCollection",
            "baseName": "billing_address_collection",
            "type": "CheckoutBillingAddressCollection"
        },
        {
            "name": "cancelUrl",
            "baseName": "cancel_url",
            "type": "string"
        },
        {
            "name": "clientReferenceId",
            "baseName": "client_reference_id",
            "type": "string"
        },
        {
            "name": "consent",
            "baseName": "consent",
            "type": "string"
        },
        {
            "name": "consentCollection",
            "baseName": "consent_collection",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "customText",
            "baseName": "custom_text",
            "type": "string"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "string"
        },
        {
            "name": "customerCreation",
            "baseName": "customer_creation",
            "type": "CheckoutCustomerCreation"
        },
        {
            "name": "customerDetails",
            "baseName": "customer_details",
            "type": "string"
        },
        {
            "name": "customerEmail",
            "baseName": "customer_email",
            "type": "string"
        },
        {
            "name": "deletedAt",
            "baseName": "deleted_at",
            "type": "DatabaseDeletedAt"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "invoice",
            "baseName": "invoice",
            "type": "string"
        },
        {
            "name": "invoiceCreation",
            "baseName": "invoice_creation",
            "type": "string"
        },
        {
            "name": "lineItems",
            "baseName": "line_items",
            "type": "Array<string>"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "CheckoutLocale"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "object"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "CheckoutMode"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "paymentIntent",
            "baseName": "payment_intent",
            "type": "string"
        },
        {
            "name": "paymentLink",
            "baseName": "payment_link",
            "type": "string"
        },
        {
            "name": "paymentMethodCollection",
            "baseName": "payment_method_collection",
            "type": "CheckoutPaymentMethodCollection"
        },
        {
            "name": "paymentMethodOptions",
            "baseName": "payment_method_options",
            "type": "string"
        },
        {
            "name": "paymentMethodTypes",
            "baseName": "payment_method_types",
            "type": "Array<string>"
        },
        {
            "name": "paymentStatus",
            "baseName": "payment_status",
            "type": "CheckoutPaymentStatus"
        },
        {
            "name": "phoneNumberCollection",
            "baseName": "phone_number_collection",
            "type": "boolean"
        },
        {
            "name": "recoveredFrom",
            "baseName": "recovered_from",
            "type": "string"
        },
        {
            "name": "setupIntent",
            "baseName": "setup_intent",
            "type": "string"
        },
        {
            "name": "shippingAddressCollection",
            "baseName": "shipping_address_collection",
            "type": "string"
        },
        {
            "name": "shippingCost",
            "baseName": "shipping_cost",
            "type": "string"
        },
        {
            "name": "shippingDetails",
            "baseName": "shipping_details",
            "type": "string"
        },
        {
            "name": "shippingOptions",
            "baseName": "shipping_options",
            "type": "Array<string>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CheckoutStatus"
        },
        {
            "name": "submitType",
            "baseName": "submit_type",
            "type": "CheckoutSubmitType"
        },
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "string"
        },
        {
            "name": "successUrl",
            "baseName": "success_url",
            "type": "string"
        },
        {
            "name": "taxIdCollection",
            "baseName": "tax_id_collection",
            "type": "boolean"
        },
        {
            "name": "totalDetails",
            "baseName": "total_details",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CheckoutCheckoutSession.attributeTypeMap;
    }
}

export namespace CheckoutCheckoutSession {
}
