/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum DisputeReason {
    ReasonBankCannotProcess = <any> 'bank_cannot_process',
    ReasonCheckReturned = <any> 'check_returned',
    ReasonCreditNotProcessed = <any> 'credit_not_processed',
    ReasonCustomerInitiated = <any> 'customer_initiated',
    ReasonDebitNotAuthorized = <any> 'debit_not_authorized',
    ReasonDuplicate = <any> 'duplicate',
    ReasonFraudulent = <any> 'fraudulent',
    ReasonGeneral = <any> 'general',
    ReasonIncorrectAccountDetails = <any> 'incorrect_account_details',
    ReasonInsufficientFunds = <any> 'insufficient_funds',
    ReasonProductNotReceived = <any> 'product_not_received',
    ReasonProductUnacceptable = <any> 'product_unacceptable',
    ReasonSubscriptionCanceled = <any> 'subscription_canceled',
    ReasonUnrecognized = <any> 'unrecognized'
}
