/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DatabaseDeletedAt } from './databaseDeletedAt';
import { GithubComDriver005GatewayInternalIntentCancellationReason } from './githubComDriver005GatewayInternalIntentCancellationReason';
import { GithubComDriver005GatewayInternalIntentStatus } from './githubComDriver005GatewayInternalIntentStatus';
import { IntentCaptureMethod } from './intentCaptureMethod';
import { IntentConfirmationMethod } from './intentConfirmationMethod';
import { IntentSetupFutureUsage } from './intentSetupFutureUsage';

export class IntentPaymentIntent {
    'amount'?: number;
    'amountCapturable'?: number;
    'amountDetails'?: string;
    'amountReceived'?: number;
    'automaticPaymentMethods'?: boolean;
    'canceledAt'?: number;
    'cancellationReason'?: GithubComDriver005GatewayInternalIntentCancellationReason;
    'captureMethod'?: IntentCaptureMethod;
    'clientSecret'?: string;
    'confirmationMethod'?: IntentConfirmationMethod;
    'createdAt'?: string;
    'currency'?: string;
    'customer'?: string;
    'deletedAt'?: DatabaseDeletedAt;
    'description'?: string;
    'id'?: string;
    'lastPaymentError'?: string;
    'latestCharge'?: string;
    'livemode'?: boolean;
    'metadata'?: object;
    'nextAction'?: string;
    'object'?: string;
    'paymentMethod'?: string;
    'paymentMethodOptions'?: string;
    'paymentMethodTypes'?: Array<string>;
    'processing'?: string;
    'receiptEmail'?: string;
    'review'?: string;
    'setupFutureUsage'?: IntentSetupFutureUsage;
    'shipping'?: string;
    'statementDescriptor'?: string;
    'statementDescriptorSuffix'?: string;
    'status'?: GithubComDriver005GatewayInternalIntentStatus;
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "amountCapturable",
            "baseName": "amount_capturable",
            "type": "number"
        },
        {
            "name": "amountDetails",
            "baseName": "amount_details",
            "type": "string"
        },
        {
            "name": "amountReceived",
            "baseName": "amount_received",
            "type": "number"
        },
        {
            "name": "automaticPaymentMethods",
            "baseName": "automatic_payment_methods",
            "type": "boolean"
        },
        {
            "name": "canceledAt",
            "baseName": "canceled_at",
            "type": "number"
        },
        {
            "name": "cancellationReason",
            "baseName": "cancellation_reason",
            "type": "GithubComDriver005GatewayInternalIntentCancellationReason"
        },
        {
            "name": "captureMethod",
            "baseName": "capture_method",
            "type": "IntentCaptureMethod"
        },
        {
            "name": "clientSecret",
            "baseName": "client_secret",
            "type": "string"
        },
        {
            "name": "confirmationMethod",
            "baseName": "confirmation_method",
            "type": "IntentConfirmationMethod"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "string"
        },
        {
            "name": "deletedAt",
            "baseName": "deleted_at",
            "type": "DatabaseDeletedAt"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "lastPaymentError",
            "baseName": "last_payment_error",
            "type": "string"
        },
        {
            "name": "latestCharge",
            "baseName": "latest_charge",
            "type": "string"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "object"
        },
        {
            "name": "nextAction",
            "baseName": "next_action",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "paymentMethod",
            "baseName": "payment_method",
            "type": "string"
        },
        {
            "name": "paymentMethodOptions",
            "baseName": "payment_method_options",
            "type": "string"
        },
        {
            "name": "paymentMethodTypes",
            "baseName": "payment_method_types",
            "type": "Array<string>"
        },
        {
            "name": "processing",
            "baseName": "processing",
            "type": "string"
        },
        {
            "name": "receiptEmail",
            "baseName": "receipt_email",
            "type": "string"
        },
        {
            "name": "review",
            "baseName": "review",
            "type": "string"
        },
        {
            "name": "setupFutureUsage",
            "baseName": "setup_future_usage",
            "type": "IntentSetupFutureUsage"
        },
        {
            "name": "shipping",
            "baseName": "shipping",
            "type": "string"
        },
        {
            "name": "statementDescriptor",
            "baseName": "statement_descriptor",
            "type": "string"
        },
        {
            "name": "statementDescriptorSuffix",
            "baseName": "statement_descriptor_suffix",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "GithubComDriver005GatewayInternalIntentStatus"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IntentPaymentIntent.attributeTypeMap;
    }
}

export namespace IntentPaymentIntent {
}
