/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DatabaseDeletedAt } from './databaseDeletedAt';
import { MandateStatus } from './mandateStatus';
import { MandateType } from './mandateType';

export class MandateMandate {
    'createdAt'?: string;
    'deletedAt'?: DatabaseDeletedAt;
    'id'?: string;
    'livemode'?: boolean;
    'metadata'?: object;
    'object'?: string;
    'paymentMethod'?: string;
    'paymentMethodDetails'?: string;
    'singleUse'?: string;
    'status'?: MandateStatus;
    'type'?: MandateType;
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "deletedAt",
            "baseName": "deleted_at",
            "type": "DatabaseDeletedAt"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "object"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "paymentMethod",
            "baseName": "payment_method",
            "type": "string"
        },
        {
            "name": "paymentMethodDetails",
            "baseName": "payment_method_details",
            "type": "string"
        },
        {
            "name": "singleUse",
            "baseName": "single_use",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "MandateStatus"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "MandateType"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MandateMandate.attributeTypeMap;
    }
}

export namespace MandateMandate {
}
