/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DatabaseDeletedAt } from './databaseDeletedAt';
import { PayoutMethod } from './payoutMethod';
import { PayoutSourceType } from './payoutSourceType';
import { PayoutStatus } from './payoutStatus';
import { PayoutType } from './payoutType';

export class PayoutPayout {
    'amount'?: number;
    'arrivalDate'?: number;
    'automatic'?: boolean;
    'balanceTransaction'?: string;
    'createdAt'?: string;
    'currency'?: string;
    'deletedAt'?: DatabaseDeletedAt;
    'description'?: string;
    'destination'?: string;
    'failureBalanceTransaction'?: string;
    'failureCode'?: string;
    'failureMessage'?: string;
    'id'?: string;
    'livemode'?: boolean;
    'metadata'?: object;
    'method'?: PayoutMethod;
    'object'?: string;
    'originalPayout'?: string;
    'reversedBy'?: string;
    'sourceType'?: PayoutSourceType;
    'statementDescriptor'?: string;
    'status'?: PayoutStatus;
    'type'?: PayoutType;
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "arrivalDate",
            "baseName": "arrival_date",
            "type": "number"
        },
        {
            "name": "automatic",
            "baseName": "automatic",
            "type": "boolean"
        },
        {
            "name": "balanceTransaction",
            "baseName": "balance_transaction",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "deletedAt",
            "baseName": "deleted_at",
            "type": "DatabaseDeletedAt"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "string"
        },
        {
            "name": "failureBalanceTransaction",
            "baseName": "failure_balance_transaction",
            "type": "string"
        },
        {
            "name": "failureCode",
            "baseName": "failure_code",
            "type": "string"
        },
        {
            "name": "failureMessage",
            "baseName": "failure_message",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "object"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "PayoutMethod"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "originalPayout",
            "baseName": "original_payout",
            "type": "string"
        },
        {
            "name": "reversedBy",
            "baseName": "reversed_by",
            "type": "string"
        },
        {
            "name": "sourceType",
            "baseName": "source_type",
            "type": "PayoutSourceType"
        },
        {
            "name": "statementDescriptor",
            "baseName": "statement_descriptor",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PayoutStatus"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PayoutType"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PayoutPayout.attributeTypeMap;
    }
}

export namespace PayoutPayout {
}
