/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum SourceType {
    TypeAchreusableTransfer = <any> 'ach_reusable_transfer',
    TypeAchDebit = <any> 'ach_debit',
    TypeAlipay = <any> 'alipay',
    TypeBancontact = <any> 'bancontact',
    TypeCard = <any> 'card',
    TypeCardPresent = <any> 'card_present',
    TypeEps = <any> 'eps',
    TypeGiropay = <any> 'giropay',
    TypeIdeal = <any> 'ideal',
    TypeMultibanco = <any> 'multibanco',
    TypeKlarna = <any> 'klarna',
    TypeP24 = <any> 'p24',
    TypeSepaDebit = <any> 'sepa_debit',
    TypeSofort = <any> 'sofort',
    TypeThreeDSecure = <any> 'three_d_secure',
    TypeWechat = <any> 'wechat'
}
