/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class BankStatus.
* @enum {}
* @readonly
*/
export default class BankStatus {
    
        /**
         * value: "new"
         * @const
         */
        "StatusNew" = "new";

    
        /**
         * value: "validated"
         * @const
         */
        "StatusValidated" = "validated";

    
        /**
         * value: "verified"
         * @const
         */
        "StatusVerified" = "verified";

    
        /**
         * value: "verification_failed"
         * @const
         */
        "StatusVerificationFailed" = "verification_failed";

    
        /**
         * value: "errored"
         * @const
         */
        "StatusErrored" = "errored";

    

    /**
    * Returns a <code>BankStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/BankStatus} The enum <code>BankStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

