/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CardAddressLine1Check.
* @enum {}
* @readonly
*/
export default class CardAddressLine1Check {
    
        /**
         * value: "pass"
         * @const
         */
        "AddressLine1CheckPass" = "pass";

    
        /**
         * value: "fail"
         * @const
         */
        "AddressLine1CheckFail" = "fail";

    
        /**
         * value: "unavailable"
         * @const
         */
        "AddressLine1CheckUnavailable" = "unavailable";

    
        /**
         * value: "unchecked"
         * @const
         */
        "AddressLine1CheckUnchecked" = "unchecked";

    

    /**
    * Returns a <code>CardAddressLine1Check</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CardAddressLine1Check} The enum <code>CardAddressLine1Check</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

