/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CheckoutStatus.
* @enum {}
* @readonly
*/
export default class CheckoutStatus {
    
        /**
         * value: "open"
         * @const
         */
        "StatusOpen" = "open";

    
        /**
         * value: "complete"
         * @const
         */
        "StatusComplete" = "complete";

    
        /**
         * value: "expired"
         * @const
         */
        "StatusExpired" = "expired";

    

    /**
    * Returns a <code>CheckoutStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CheckoutStatus} The enum <code>CheckoutStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

