/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CustomerTaxExempt.
* @enum {}
* @readonly
*/
export default class CustomerTaxExempt {
    
        /**
         * value: "none"
         * @const
         */
        "TaxExemptNone" = "none";

    
        /**
         * value: "exempt"
         * @const
         */
        "TaxExemptExempt" = "exempt";

    
        /**
         * value: "reverse"
         * @const
         */
        "TaxExemptReverse" = "reverse";

    

    /**
    * Returns a <code>CustomerTaxExempt</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CustomerTaxExempt} The enum <code>CustomerTaxExempt</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

