/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class GithubComDriver005GatewayInternalIntentCancellationReason.
* @enum {}
* @readonly
*/
export default class GithubComDriver005GatewayInternalIntentCancellationReason {
    
        /**
         * value: "duplicate"
         * @const
         */
        "CancellationReasonDuplicate" = "duplicate";

    
        /**
         * value: "fraudulent"
         * @const
         */
        "CancellationReasonFraudulent" = "fraudulent";

    
        /**
         * value: "requested_by_customer"
         * @const
         */
        "CancellationReasonRequestedByCustomer" = "requested_by_customer";

    
        /**
         * value: "abandoned"
         * @const
         */
        "CancellationReasonAbandoned" = "abandoned";

    
        /**
         * value: "failed_invoice"
         * @const
         */
        "CancellationReasonFailedInvoice" = "failed_invoice";

    
        /**
         * value: "void_invoice"
         * @const
         */
        "CancellationReasonVoidInvoice" = "void_invoice";

    
        /**
         * value: "automatic"
         * @const
         */
        "CancellationReasonAutomatic" = "automatic";

    

    /**
    * Returns a <code>GithubComDriver005GatewayInternalIntentCancellationReason</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/GithubComDriver005GatewayInternalIntentCancellationReason} The enum <code>GithubComDriver005GatewayInternalIntentCancellationReason</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

