/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class IntentCaptureMethod.
* @enum {}
* @readonly
*/
export default class IntentCaptureMethod {
    
        /**
         * value: "automatic"
         * @const
         */
        "CaptureMethodAutomatic" = "automatic";

    
        /**
         * value: "manual"
         * @const
         */
        "CaptureMethodManual" = "manual";

    

    /**
    * Returns a <code>IntentCaptureMethod</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/IntentCaptureMethod} The enum <code>IntentCaptureMethod</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

