/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DatabaseDeletedAt from './DatabaseDeletedAt';
import GithubComDriver005GatewayInternalSetupIntentCancellationReason from './GithubComDriver005GatewayInternalSetupIntentCancellationReason';
import GithubComDriver005GatewayInternalSetupIntentStatus from './GithubComDriver005GatewayInternalSetupIntentStatus';
import IntentUsage from './IntentUsage';

/**
 * The IntentSetupIntent model module.
 * @module model/IntentSetupIntent
 * @version 2.0
 */
class IntentSetupIntent {
    /**
     * Constructs a new <code>IntentSetupIntent</code>.
     * @alias module:model/IntentSetupIntent
     */
    constructor() { 
        
        IntentSetupIntent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IntentSetupIntent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IntentSetupIntent} obj Optional instance to populate.
     * @return {module:model/IntentSetupIntent} The populated <code>IntentSetupIntent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IntentSetupIntent();

            if (data.hasOwnProperty('attach_to_self')) {
                obj['attach_to_self'] = ApiClient.convertToType(data['attach_to_self'], 'Boolean');
            }
            if (data.hasOwnProperty('cancellation_reason')) {
                obj['cancellation_reason'] = GithubComDriver005GatewayInternalSetupIntentCancellationReason.constructFromObject(data['cancellation_reason']);
            }
            if (data.hasOwnProperty('client_secret')) {
                obj['client_secret'] = ApiClient.convertToType(data['client_secret'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = ApiClient.convertToType(data['customer'], 'String');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = DatabaseDeletedAt.constructFromObject(data['deleted_at']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('flow_directions')) {
                obj['flow_directions'] = ApiClient.convertToType(data['flow_directions'], ['String']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('last_setup_error')) {
                obj['last_setup_error'] = ApiClient.convertToType(data['last_setup_error'], 'String');
            }
            if (data.hasOwnProperty('livemode')) {
                obj['livemode'] = ApiClient.convertToType(data['livemode'], 'Boolean');
            }
            if (data.hasOwnProperty('mandate')) {
                obj['mandate'] = ApiClient.convertToType(data['mandate'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('next_action')) {
                obj['next_action'] = ApiClient.convertToType(data['next_action'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('payment_method')) {
                obj['payment_method'] = ApiClient.convertToType(data['payment_method'], 'String');
            }
            if (data.hasOwnProperty('payment_method_types')) {
                obj['payment_method_types'] = ApiClient.convertToType(data['payment_method_types'], ['String']);
            }
            if (data.hasOwnProperty('single_use_mandate')) {
                obj['single_use_mandate'] = ApiClient.convertToType(data['single_use_mandate'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = GithubComDriver005GatewayInternalSetupIntentStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('usage')) {
                obj['usage'] = IntentUsage.constructFromObject(data['usage']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IntentSetupIntent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IntentSetupIntent</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['client_secret'] && !(typeof data['client_secret'] === 'string' || data['client_secret'] instanceof String)) {
            throw new Error("Expected the field `client_secret` to be a primitive type in the JSON string but got " + data['client_secret']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['customer'] && !(typeof data['customer'] === 'string' || data['customer'] instanceof String)) {
            throw new Error("Expected the field `customer` to be a primitive type in the JSON string but got " + data['customer']);
        }
        // validate the optional field `deleted_at`
        if (data['deleted_at']) { // data not null
          DatabaseDeletedAt.validateJSON(data['deleted_at']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['flow_directions'])) {
            throw new Error("Expected the field `flow_directions` to be an array in the JSON data but got " + data['flow_directions']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['last_setup_error'] && !(typeof data['last_setup_error'] === 'string' || data['last_setup_error'] instanceof String)) {
            throw new Error("Expected the field `last_setup_error` to be a primitive type in the JSON string but got " + data['last_setup_error']);
        }
        // ensure the json data is a string
        if (data['mandate'] && !(typeof data['mandate'] === 'string' || data['mandate'] instanceof String)) {
            throw new Error("Expected the field `mandate` to be a primitive type in the JSON string but got " + data['mandate']);
        }
        // ensure the json data is a string
        if (data['next_action'] && !(typeof data['next_action'] === 'string' || data['next_action'] instanceof String)) {
            throw new Error("Expected the field `next_action` to be a primitive type in the JSON string but got " + data['next_action']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // ensure the json data is a string
        if (data['payment_method'] && !(typeof data['payment_method'] === 'string' || data['payment_method'] instanceof String)) {
            throw new Error("Expected the field `payment_method` to be a primitive type in the JSON string but got " + data['payment_method']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['payment_method_types'])) {
            throw new Error("Expected the field `payment_method_types` to be an array in the JSON data but got " + data['payment_method_types']);
        }
        // ensure the json data is a string
        if (data['single_use_mandate'] && !(typeof data['single_use_mandate'] === 'string' || data['single_use_mandate'] instanceof String)) {
            throw new Error("Expected the field `single_use_mandate` to be a primitive type in the JSON string but got " + data['single_use_mandate']);
        }
        // ensure the json data is a string
        if (data['updated_at'] && !(typeof data['updated_at'] === 'string' || data['updated_at'] instanceof String)) {
            throw new Error("Expected the field `updated_at` to be a primitive type in the JSON string but got " + data['updated_at']);
        }

        return true;
    }


}



/**
 * @member {Boolean} attach_to_self
 */
IntentSetupIntent.prototype['attach_to_self'] = undefined;

/**
 * @member {module:model/GithubComDriver005GatewayInternalSetupIntentCancellationReason} cancellation_reason
 */
IntentSetupIntent.prototype['cancellation_reason'] = undefined;

/**
 * @member {String} client_secret
 */
IntentSetupIntent.prototype['client_secret'] = undefined;

/**
 * @member {String} created_at
 */
IntentSetupIntent.prototype['created_at'] = undefined;

/**
 * @member {String} customer
 */
IntentSetupIntent.prototype['customer'] = undefined;

/**
 * @member {module:model/DatabaseDeletedAt} deleted_at
 */
IntentSetupIntent.prototype['deleted_at'] = undefined;

/**
 * @member {String} description
 */
IntentSetupIntent.prototype['description'] = undefined;

/**
 * @member {Array.<String>} flow_directions
 */
IntentSetupIntent.prototype['flow_directions'] = undefined;

/**
 * @member {String} id
 */
IntentSetupIntent.prototype['id'] = undefined;

/**
 * @member {String} last_setup_error
 */
IntentSetupIntent.prototype['last_setup_error'] = undefined;

/**
 * @member {Boolean} livemode
 */
IntentSetupIntent.prototype['livemode'] = undefined;

/**
 * @member {String} mandate
 */
IntentSetupIntent.prototype['mandate'] = undefined;

/**
 * @member {Object} metadata
 */
IntentSetupIntent.prototype['metadata'] = undefined;

/**
 * @member {String} next_action
 */
IntentSetupIntent.prototype['next_action'] = undefined;

/**
 * @member {String} object
 */
IntentSetupIntent.prototype['object'] = undefined;

/**
 * @member {String} payment_method
 */
IntentSetupIntent.prototype['payment_method'] = undefined;

/**
 * @member {Array.<String>} payment_method_types
 */
IntentSetupIntent.prototype['payment_method_types'] = undefined;

/**
 * @member {String} single_use_mandate
 */
IntentSetupIntent.prototype['single_use_mandate'] = undefined;

/**
 * @member {module:model/GithubComDriver005GatewayInternalSetupIntentStatus} status
 */
IntentSetupIntent.prototype['status'] = undefined;

/**
 * @member {String} updated_at
 */
IntentSetupIntent.prototype['updated_at'] = undefined;

/**
 * @member {module:model/IntentUsage} usage
 */
IntentSetupIntent.prototype['usage'] = undefined;






export default IntentSetupIntent;

