/**
 * Fiber Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PriceTaxBehavior.
* @enum {}
* @readonly
*/
export default class PriceTaxBehavior {
    
        /**
         * value: "inclusive"
         * @const
         */
        "TaxBehaviorInclusive" = "inclusive";

    
        /**
         * value: "exclusive"
         * @const
         */
        "TaxBehaviorExclusive" = "exclusive";

    
        /**
         * value: "unspecified"
         * @const
         */
        "TaxBehaviorUnspecified" = "unspecified";

    

    /**
    * Returns a <code>PriceTaxBehavior</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PriceTaxBehavior} The enum <code>PriceTaxBehavior</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

